properties:
  rates:
    app_id:
    url: https://openexchangerates.org/api
    historical_endpoint: historical
    latest_endpoint: latest.json
  gifs:
    api_key:
    url: api.giphy.com/v1/gifs/random